sudo: required
dist: trusty
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
deploy:
  - provider: rubygems
    gem: ruby-puppetdb
    gemspec: ruby-puppetdb.gemspec
    api_key:
      secure: "IgMVf0Fa8Tqkz7ow402fR4lcxyv2vmMleYunZaJni3jKpDp/vzkaBsd7XMK7UMGsI70UVNP+CdSvFODlh/Ceqkoy8wqc01+c7+NWvKHczzW+/Q2knReboQ+58+Wsd0v4lNb8sWgqgco9pY7hUUGNJgw3rQqCcNuc4fCJfj0pzuk="
    on:
      all_branches: true
      tags: true
      rvm: 2.1
  - provider: puppetforge
    user: dalen
    password:
      secure: "cITJDXn+Vg5l5lMr9st75sy59xfAU6DuZrgedO68SGN12QAqWkj98RAczbcWCeVdJNAp9XDa5M8Zw29X0iv8pgcmFB+p8RugfT7+WHi8Yz0BXmnin1GoQfy1VQGmPL/lxf4xTSHRxYAQrL3Qzd3BbPh/w+QRIET4ZYSbEjklRXY="
    on:
      all_branches: true
      tags: true
      rvm: 2.1
